export const commonIconRootCheck: string;
export const commonIconRootChevronDown: string;
export const commonIconRootChevronUp: string;
export const commonIconRootClose: string;
export const commonIconRootEdit: string;
export const commonIconRootLogo: string;
export const commonIconRootMagnifier: string;
export const commonIconRootTrash: string;
export const commonIconRootTrashOrange: string;